[[ariaid-title1]]
== Особенности использования механизма распространения компонентов

. [.dfn .term]_Справочник компонентов_ предназначен для распространения только .NET-сборок.
. Распространяемые сборки загружаются в папку [.ph .filepath]`%temp%\DV5.5\Deploy\[Группа компонентов]\[Название компонента]_[Версия компонента]` компьютера пользователя Docsvision. Для подключения .NET-сборки к Windows-клиенту рекомендуется указывать полное имени сборки, вместо абсолютного пути к ней.
. Файлы, добавляемые в [.dfn .term]_Справочник компонентов_, должны иметь уникальные названия.
. Установка компонентов выполняется только по запросу, который наступает при обращении Windows-клиента к данным компонентам.
. Журналирование операций установки компонентов осуществляется Windows-клиентом. Включите расширенное логирование Windows-клиента, чтобы проанализировать работу механизма распространения компонентов на данном компьютере.

*Parent topic:* xref:../topics/ComponentsDirectory.adoc[Справочник компонентов]
