[[ariaid-title1]]
== Область «Категории»

Область [.dfn .term]_Категории_ включает дерево системных настроек, которое по умолчанию содержит следующие ветви:

* [.ph .uicontrol]*Общие настройки* – содержит стандартные настройки сканирования, ограничений для прикладываемых файлов, а также переключатель режима расчёта дискреционных прав.
* [.ph .uicontrol]*Windows-клиент* – содержит настройки базового модуля «Docsvision 5. Windows-клиент».
* [.ph .uicontrol]*Настройки журнала* – содержит настройки протоколирования пользовательских операций.
* [.ph .uicontrol]*Базовые объекты* – содержит настройки базового модуля «Docsvision 5. Базовые объекты».
* [.ph .uicontrol]*Делопроизводство* – содержит настройки базового модуля «Docsvision 5. Делопроизводство 4.5».
* [.ph .uicontrol]*Настройки Workflow* – содержит настройки базового модуля «Docsvision 5. Управление процессами».

Ветки с настройками модулей отображаются, если соответствующие модули Docsvision установлены.

*На уровень выше:* xref:../topics/DS_Interface.adoc[Интерфейс справочника]
