= Аннотация

[#purpose]
== Назначение документа

Документация в данном разделе содержит описание Конструкторов и справочников {dv}.

Документ предназначен для администраторов и инженеров системы {dv}.

[#arrangement]
== Как организована документация модуля

Документация содержит описание всех справочников. Справочники поставляются с базовыми модулями:

.Поставляются с модулем {pl}:
* xref:foldertypes:folder-types-directory.adoc[Справочник типов папок],
* xref:systemsettings:system-settings.adoc[Системные настройки],
* xref:components:components-directory.adoc[Справочник компонентов].

.Поставляются с модулем {bo}:
* Потом добавлю

Описание справочника включает обзор пользовательского интерфейса и руководство по работе со справочником.

[CAUTION]
====
Описание конструкторов и справочников модуля {wc} см. в документации модуля {wc}:

* xref:webclient:user:directories/partners/directory.adoc[]
* xref:webclient:user:directories/nomenclature/directory.adoc[]
* xref:webclient:user:directories/staff/directory.adoc[]
====
