= Общие сведения

[#purpose]
== Назначение документации

Документация в данном разделе содержит описание Конструкторов и справочников {dv}.

Документ предназначен для администраторов и инженеров системы {dv}.

[#arrangement]
== Как организована документация модуля

Документация содержит описание справочников, поставляемых с модулем {pl}:

* "xref:foldertypes:directory.adoc[Справочник типов папок]".
* "xref:systemsettings:directory.adoc[Системные настройки]".
* "xref:components:directory.adoc[Справочник компонентов]".

Конструкторы и справочники, поставляемые с модулем _{bo}_ описаны в следующих разделах документации:

* "xref:card-kinds:directory.adoc[]".
* "xref:categories:directory.adoc[]".
* "xref:links:directory.adoc[]".
* "xref:partners:directory.adoc[]".
* "xref:servers:directory.adoc[]".
* "xref:signatures:directory.adoc[]".
* "xref:staff:directory.adoc[]".
* "xref:directories:designer.adoc[]".
* "xref:layouts:designer.adoc[]".
* "xref:numeration:designer.adoc[]".
* "xref:roles:designer.adoc[]".
* "xref:scripts:designer.adoc[]".
* "xref:states:designer.adoc[]".

Описание справочника включает обзор пользовательского интерфейса и руководство по работе со справочником.

[WARNING]
====
Описание конструкторов и справочников модуля {wc} см. в документации модуля {wc}:

* "xref:webclient:user:directories/partners/directory.adoc[]"
* "xref:webclient:user:directories/nomenclature/directory.adoc[]"
* "xref:webclient:user:directories/staff/directory.adoc[]"
* "xref:5.5.17@webclient:user:directories/powers/directory.adoc[]"
====

[#conditions]
== Условия использования конструкторов и справочников

. При работе с конструкторами и справочниками {dv} *ЗАПРЕЩЕНО* изменять настройки корневых видов карточек, добавляемых модулем _{bo}_: _Документ_, _Задание_, _Группа заданий_, _Согласование_, _Этап согласования_, _Маршрут согласования_ и других.
+
Вместо изменения корневого вида создайте дочерний вид, настройки которого можно изменять без ограничений.
+
. Для возможности работы со справочниками и конструкторами {wincl} или РМА должен быть запущен _администратором {dv}_.
. *Рекомендуется* прослушать курс http://edu.{dv}.com/spisok-kursov/DV005.html[DV005 Основы конструирования решений в {dv}], чтобы овладеть навыками настройки _Решений_ на платформе {dv} с использованием справочников и конструкторов.
