= Особенности именования классов скриптов карточек

По умолчанию название класса скрипта карточки связано с названием вида карточек, которому принадлежит скрипт. Название класса формируется по шаблону: `ТипКарточки.НазваниеВида карточекScript`. Если название класса не соответствует шаблону, то данный скрипт не будет использоваться при работе с карточкой.

Если в названии вида карточки присутствуют знаки препинания, тире или пробелы, то в названии класса данные символы будут заменены на символ `_`. К примеру, если вид имеет название `Простое задание УД` (в названии присутствуют пробелы), класс будет назван `Простое_задание_УД`.

NOTE: Не создавайте виды карточек, отличающиеся в названии только знаком препинания. Например, `Простое задание УД`, `Простое-задание,УД` -- это может привести к некорректной работе скриптов данных видов карточек.

Также можно "отвязать" название класса от названия вида карточек. Для этого отметьте класс скрипта карточки атрибутом `CardKindScriptClass`:

[source,csharp]
----
[CardKindScriptClass]
public class DocumentSampleScript : DocumentDMScript
----

Класс, который отмечен атрибутом `CardKindScriptClass`, считается классом скрипта карточки, независимо его названия.
